[
    {
        "type": "Enemy",
        "name": "Poring",
        "level": 1,
        "experience": 10,
        "class": "monster",
        "hp": 50,
        "maxHp": 50,
        "mp": 0,
        "atk": 10,
        "def": 0,
        "atkDelay": 80,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 2
    },
    {
        "type": "Enemy",
        "name": "Drops",
        "level": 2,
        "experience": 20,
        "class": "monster",
        "hp": 100,
        "maxHp": 100,
        "mp": 0,
        "atk": 15,
        "def": 2,
        "atkDelay": 100,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 5
    },
    {
        "type": "Enemy",
        "name": "Poporing",
        "level": 5,
        "experience": 50,
        "class": "monster",
        "hp": 200,
        "maxHp": 200,
        "mp": 0,
        "atk": 20,
        "def": 5,
        "atkDelay": 120,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 30
    },
    {
        "type": "Enemy",
        "name": "Marine",
        "level": 7,
        "experience": 100,
        "class": "monster",
        "hp": 300,
        "maxHp": 300,
        "mp": 0,
        "atk": 25,
        "def": 7,
        "atkDelay": 180,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 100
    },
    {
        "type": "Enemy",
        "name": "Poring_King",
        "level": 10,
        "experience": 1000,
        "class": "boss",
        "hp": 1000,
        "maxHp": 1000,
        "mp": 0,
        "atk": 50,
        "def": 20,
        "atkDelay": 180,
        "atkSpeed": 10,
        "zeny": 1000,
        "minions": 6
    },

    {
        "type": "Enemy",
        "name": "Fabre",
        "level": 3,
        "experience": 10,
        "class": "monster",
        "hp": 80,
        "maxHp": 80,
        "mp": 0,
        "atk": 20,
        "def": 2,
        "atkDelay": 60,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 10
    },
    {
        "type": "Enemy",
        "name": "Lunatic",
        "level": 5,
        "experience": 30,
        "class": "monster",
        "hp": 100,
        "maxHp": 100,
        "mp": 0,
        "atk": 20,
        "def": 4,
        "atkDelay": 30,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 30
    },
    {
        "type": "Enemy",
        "name": "Rodra",
        "level": 8,
        "experience": 50,
        "class": "monster",
        "hp": 200,
        "maxHp": 200,
        "mp": 0,
        "atk": 40,
        "def": 10,
        "atkDelay": 80,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 50
    },
    {
        "type": "Enemy",
        "name": "Rocker",
        "level": 12,
        "experience": 100,
        "class": "monster",
        "hp": 300,
        "maxHp": 300,
        "mp": 0,
        "atk": 50,
        "def": 7,
        "atkDelay": 180,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 100
    },
    {
        "type": "Enemy",
        "name": "Eclipse",
        "level": 20,
        "experience": 1000,
        "class": "boss",
        "hp": 4000,
        "maxHp": 4000,
        "mp": 0,
        "atk": 100,
        "def": 40,
        "atkDelay": 120,
        "atkSpeed": 10,
        "reviveDelay": 60,
        "zeny": 10000,
        "minions": 6
    }
]
